CREATE TABLE "sell_requests" (
  "sell_req_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sell_amount" decimal NOT NULL,
  "currency" varchar NOT NULL,
  "tg_username" varchar NOT NULL,
  "sell_by_card" bool,
  "sell_amount_by_card" decimal,
  "sell_by_cash" bool,
  "sell_amunt_by_cash" decimal,
  "sell_exchange_rate" decimal,
  "is_actual" bool DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "comment" varchar
);

CREATE TABLE "buy_requests" (
  "buy_req_id" uuid UNIQUE PRIMARY KEY,
  "sell_req_id" integer NOT NULL,
  "buy_amount" decimal NOT NULL,
  "currency" varchar NOT NULL,
  "tg_username" varchar NOT NULL,
  "buy_by_card" bool,
  "buy_amount_by_card" decimal,
  "buy_by_cash" bool,
  "buy_amunt_by_cash" decimal,
  "is_successful" bool DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "expires_at" timestamptz NOT NULL DEFAULT (now() + interval '1 hour')
);

CREATE INDEX ON "sell_requests" ("sell_req_id");
ALTER TABLE "buy_requests" ADD CONSTRAINT "buy_requests" FOREIGN KEY ("sell_req_id") REFERENCES "sell_requests" ("sell_req_id");
