// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BuyRequest struct {
	BuyReqID        uuid.UUID   `json:"buy_req_id"`
	SellReqID       int32       `json:"sell_req_id"`
	BuyAmount       int64       `json:"buy_amount"`
	TgUsername      string      `json:"tg_username"`
	BuyByCard       pgtype.Bool `json:"buy_by_card"`
	BuyAmountByCard pgtype.Int8 `json:"buy_amount_by_card"`
	BuyByCash       pgtype.Bool `json:"buy_by_cash"`
	BuyAmountByCash pgtype.Int8 `json:"buy_amount_by_cash"`
	IsSuccessful    pgtype.Bool `json:"is_successful"`
	CreatedAt       time.Time   `json:"created_at"`
	ExpiresAt       time.Time   `json:"expires_at"`
}

type SellRequest struct {
	SellReqID        int32       `json:"sell_req_id"`
	SellAmount       int64       `json:"sell_amount"`
	CurrencyFrom     string      `json:"currency_from"`
	CurrencyTo       string      `json:"currency_to"`
	TgUsername       string      `json:"tg_username"`
	SellByCard       pgtype.Bool `json:"sell_by_card"`
	SellAmountByCard pgtype.Int8 `json:"sell_amount_by_card"`
	SellByCash       pgtype.Bool `json:"sell_by_cash"`
	SellAmountByCash pgtype.Int8 `json:"sell_amount_by_cash"`
	SellExchangeRate pgtype.Int8 `json:"sell_exchange_rate"`
	IsActual         pgtype.Bool `json:"is_actual"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	IsDeleted        pgtype.Bool `json:"is_deleted"`
	Comment          string      `json:"comment"`
}
