// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BuyRequest struct {
	BuyReqID             uuid.UUID          `json:"buy_req_id"`
	SellReqID            int32              `json:"sell_req_id"`
	BuyTotalAmount       int64              `json:"buy_total_amount"`
	TelegramID           int64              `json:"telegram_id"`
	TgUsername           string             `json:"tg_username"`
	BuyByCard            pgtype.Bool        `json:"buy_by_card"`
	BuyAmountByCard      pgtype.Int8        `json:"buy_amount_by_card"`
	BuyByCash            pgtype.Bool        `json:"buy_by_cash"`
	BuyAmountByCash      pgtype.Int8        `json:"buy_amount_by_cash"`
	CloseConfirmBySeller pgtype.Bool        `json:"close_confirm_by_seller"`
	CloseConfirmByBuyer  pgtype.Bool        `json:"close_confirm_by_buyer"`
	SellerConfirmedAt    pgtype.Timestamptz `json:"seller_confirmed_at"`
	BuyerConfirmedAt     pgtype.Timestamptz `json:"buyer_confirmed_at"`
	IsClosed             pgtype.Bool        `json:"is_closed"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	CreatedAt            time.Time          `json:"created_at"`
	ExpiresAt            time.Time          `json:"expires_at"`
}

type LockedAmount struct {
	ID                int32              `json:"id"`
	SellReqID         int32              `json:"sell_req_id"`
	BuyReqID          uuid.UUID          `json:"buy_req_id"`
	LockedTotalAmount int64              `json:"locked_total_amount"`
	LockedByCard      pgtype.Int8        `json:"locked_by_card"`
	LockedByCash      pgtype.Int8        `json:"locked_by_cash"`
	CreatedAt         time.Time          `json:"created_at"`
	IsReleased        pgtype.Bool        `json:"is_released"`
	ReleasedAt        pgtype.Timestamptz `json:"released_at"`
}

type SellRequest struct {
	SellReqID        int32       `json:"sell_req_id"`
	SellTotalAmount  int64       `json:"sell_total_amount"`
	SellMoneySource  string      `json:"sell_money_source"`
	CurrencyFrom     string      `json:"currency_from"`
	CurrencyTo       string      `json:"currency_to"`
	TelegramID       int64       `json:"telegram_id"`
	TgUsername       string      `json:"tg_username"`
	SellByCard       pgtype.Bool `json:"sell_by_card"`
	SellAmountByCard pgtype.Int8 `json:"sell_amount_by_card"`
	SellByCash       pgtype.Bool `json:"sell_by_cash"`
	SellAmountByCash pgtype.Int8 `json:"sell_amount_by_cash"`
	SellExchangeRate pgtype.Int8 `json:"sell_exchange_rate"`
	IsActual         pgtype.Bool `json:"is_actual"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	IsDeleted        pgtype.Bool `json:"is_deleted"`
	Comment          string      `json:"comment"`
}

type User struct {
	TelegramID int64       `json:"telegram_id"`
	TgUsername string      `json:"tg_username"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}
