// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseBuyRequest(ctx context.Context, buyReqID uuid.UUID) (BuyRequest, error)
	CreateBuyRequest(ctx context.Context, arg CreateBuyRequestParams) (BuyRequest, error)
	CreateSellRequest(ctx context.Context, arg CreateSellRequestParams) (SellRequest, error)
	DeleteBuyRequest(ctx context.Context, buyReqID uuid.UUID) error
	DeleteSellRequest(ctx context.Context, sellReqID int32) (SellRequest, error)
	GetBuyRequestById(ctx context.Context, buyReqID uuid.UUID) (BuyRequest, error)
	GetSellRequestById(ctx context.Context, sellReqID int32) (SellRequest, error)
	ListBuyRequests(ctx context.Context, arg ListBuyRequestsParams) ([]BuyRequest, error)
	ListSellRequests(ctx context.Context, arg ListSellRequestsParams) ([]SellRequest, error)
	UpdateBuyRequest(ctx context.Context, arg UpdateBuyRequestParams) (BuyRequest, error)
	UpdateSellRequest(ctx context.Context, arg UpdateSellRequestParams) (SellRequest, error)
}

var _ Querier = (*Queries)(nil)
