// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSpaceMember(ctx context.Context, arg AddSpaceMemberParams) (SpaceMember, error)
	ChangeStateBuyRequest(ctx context.Context, arg ChangeStateBuyRequestParams) (BuyRequest, error)
	CloseBuyRequestBySellRequest(ctx context.Context, sellReqID int32) error
	CloseConfirmByBuyer(ctx context.Context, arg CloseConfirmByBuyerParams) error
	CloseConfirmBySeller(ctx context.Context, arg CloseConfirmBySellerParams) error
	CountOfBuyRequests(ctx context.Context, sellReqID int32) (int64, error)
	CountOfBuyRequestsByTelegramId(ctx context.Context, telegramID int64) (int64, error)
	CountOfSellRequests(ctx context.Context) (int64, error)
	CountOfSellRequestsByTelegramId(ctx context.Context, telegramID int64) (int64, error)
	CreateBuyRequest(ctx context.Context, arg CreateBuyRequestParams) (BuyRequest, error)
	CreateLockedAmount(ctx context.Context, arg CreateLockedAmountParams) (LockedAmount, error)
	CreateSellRequest(ctx context.Context, arg CreateSellRequestParams) (SellRequest, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBuyRequest(ctx context.Context, buyReqID uuid.UUID) error
	DeleteSellRequest(ctx context.Context, sellReqID int32) (pgtype.Bool, error)
	DeleteSpace(ctx context.Context, spaceID uuid.UUID) error
	DeleteSpaceMember(ctx context.Context, arg DeleteSpaceMemberParams) error
	DeleteUser(ctx context.Context, telegramID int64) error
	GetBuyRequestById(ctx context.Context, buyReqID uuid.UUID) (BuyRequest, error)
	GetLockedAmount(ctx context.Context, buyReqID uuid.UUID) (LockedAmount, error)
	GetLockedAmountBySellRequest(ctx context.Context, sellReqID int32) ([]LockedAmount, error)
	GetSellRequestById(ctx context.Context, sellReqID int32) (SellRequest, error)
	GetSellRequestForUpdate(ctx context.Context, sellReqID int32) (SellRequest, error)
	GetSpaceByCreatorId(ctx context.Context, creatorID pgtype.Int8) ([]Space, error)
	GetSpaceBySpaceId(ctx context.Context, spaceID uuid.UUID) (Space, error)
	GetSpaceIdByUserId(ctx context.Context, userID int64) ([]uuid.UUID, error)
	GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (SpaceMember, error)
	GetSpaceMembersCount(ctx context.Context, spaceID uuid.UUID) (int64, error)
	GetUser(ctx context.Context, telegramID int64) (User, error)
	IsUserInSameSpaceAsSeller(ctx context.Context, arg IsUserInSameSpaceAsSellerParams) (bool, error)
	IsUserInSpace(ctx context.Context, arg IsUserInSpaceParams) (bool, error)
	ListBuyRequests(ctx context.Context, arg ListBuyRequestsParams) ([]BuyRequest, error)
	ListBuyRequestsByTelegramId(ctx context.Context, arg ListBuyRequestsByTelegramIdParams) ([]BuyRequest, error)
	ListExpiredBuyRequests(ctx context.Context) ([]BuyRequest, error)
	ListFirstMySpacesByNameAsc(ctx context.Context, arg ListFirstMySpacesByNameAscParams) ([]Space, error)
	ListFirstSpacesByNameAsc(ctx context.Context, limit int32) ([]Space, error)
	ListLockedAmounts(ctx context.Context, arg ListLockedAmountsParams) ([]LockedAmount, error)
	ListMySpacesAfterCursorByNameAsc(ctx context.Context, arg ListMySpacesAfterCursorByNameAscParams) ([]Space, error)
	ListMySpacesAfterCursorByNameDesc(ctx context.Context, arg ListMySpacesAfterCursorByNameDescParams) ([]Space, error)
	ListSellRequests(ctx context.Context, arg ListSellRequestsParams) ([]SellRequest, error)
	ListSellRequestsBySpace(ctx context.Context, arg ListSellRequestsBySpaceParams) ([]SellRequest, error)
	ListSellRequestsBySpaceAndTelegramID(ctx context.Context, arg ListSellRequestsBySpaceAndTelegramIDParams) ([]SellRequest, error)
	ListSellRequestsByTelegramId(ctx context.Context, arg ListSellRequestsByTelegramIdParams) ([]SellRequest, error)
	ListSpaceMembersByUsernameAsc(ctx context.Context, arg ListSpaceMembersByUsernameAscParams) ([]SpaceMember, error)
	ListSpaceMembersByUsernameDesc(ctx context.Context, arg ListSpaceMembersByUsernameDescParams) ([]SpaceMember, error)
	ListSpacesAfterCursorByNameAsc(ctx context.Context, arg ListSpacesAfterCursorByNameAscParams) ([]Space, error)
	ListSpacesAfterCursorByNameDesc(ctx context.Context, arg ListSpacesAfterCursorByNameDescParams) ([]Space, error)
	OpenCloseSellRequest(ctx context.Context, arg OpenCloseSellRequestParams) (SellRequest, error)
	ReleaseLockedAmountByBuyRequest(ctx context.Context, buyReqID uuid.UUID) error
	ReleaseLockedAmountsBySellRequest(ctx context.Context, sellReqID int32) error
	UpdateSellRequest(ctx context.Context, arg UpdateSellRequestParams) (SellRequest, error)
	UpdateSpaceInfo(ctx context.Context, arg UpdateSpaceInfoParams) (Space, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
