// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseConfirmByBuyer(ctx context.Context, arg CloseConfirmByBuyerParams) error
	CloseConfirmBySeller(ctx context.Context, arg CloseConfirmBySellerParams) error
	CreateBuyRequest(ctx context.Context, arg CreateBuyRequestParams) (BuyRequest, error)
	CreateLockedAmount(ctx context.Context, arg CreateLockedAmountParams) (LockedAmount, error)
	CreateSellRequest(ctx context.Context, arg CreateSellRequestParams) (SellRequest, error)
	DeleteBuyRequest(ctx context.Context, buyReqID uuid.UUID) error
	DeleteSellRequest(ctx context.Context, sellReqID int32) (pgtype.Bool, error)
	GetBuyRequestById(ctx context.Context, buyReqID uuid.UUID) (BuyRequest, error)
	GetLockedAmount(ctx context.Context, buyReqID uuid.UUID) (LockedAmount, error)
	GetLockedAmountBySellRequest(ctx context.Context, sellReqID int32) ([]LockedAmount, error)
	GetSellRequestById(ctx context.Context, sellReqID int32) (SellRequest, error)
	GetSellRequestForUpdate(ctx context.Context, sellReqID int32) (SellRequest, error)
	ListBuyRequests(ctx context.Context, arg ListBuyRequestsParams) ([]BuyRequest, error)
	ListLockedAmounts(ctx context.Context, arg ListLockedAmountsParams) ([]LockedAmount, error)
	ListSellRequests(ctx context.Context, arg ListSellRequestsParams) ([]SellRequest, error)
	OpenCloseBuyRequest(ctx context.Context, arg OpenCloseBuyRequestParams) (BuyRequest, error)
	OpenCloseSellRequest(ctx context.Context, arg OpenCloseSellRequestParams) (SellRequest, error)
	ReleaseLockedAmountByBuyRequest(ctx context.Context, buyReqID uuid.UUID) error
	ReleaseLockedAmountsBySellRequest(ctx context.Context, sellReqID int32) error
	UpdateBuyRequest(ctx context.Context, arg UpdateBuyRequestParams) (BuyRequest, error)
	UpdateSellRequest(ctx context.Context, arg UpdateSellRequestParams) (SellRequest, error)
}

var _ Querier = (*Queries)(nil)
