// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    telegram_id,
    tg_username,
    first_name,
    photo_url,
    last_name
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING telegram_id, tg_username, first_name, last_name, photo_url, created_at, updated_at
`

type CreateUserParams struct {
	TelegramID int64       `json:"telegram_id"`
	TgUsername string      `json:"tg_username"`
	FirstName  pgtype.Text `json:"first_name"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
	LastName   pgtype.Text `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.TgUsername,
		arg.FirstName,
		arg.PhotoUrl,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.TelegramID,
		&i.TgUsername,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE telegram_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, telegramID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT telegram_id, tg_username, first_name, last_name, photo_url, created_at, updated_at FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUser(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, telegramID)
	var i User
	err := row.Scan(
		&i.TelegramID,
		&i.TgUsername,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    tg_username = COALESCE($1, tg_username),
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    photo_url = COALESCE($4, photo_url),
    updated_at = CASE
        WHEN $1 IS NOT NULL
          OR $2 IS NOT NULL
          OR $3 IS NOT NULL
          OR $4 IS NOT NULL
        THEN now()
        ELSE updated_at
    END
WHERE telegram_id = $5
RETURNING telegram_id, tg_username, first_name, last_name, photo_url, created_at, updated_at
`

type UpdateUserParams struct {
	TgUsername pgtype.Text `json:"tg_username"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
	TelegramID int64       `json:"telegram_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.TgUsername,
		arg.FirstName,
		arg.LastName,
		arg.PhotoUrl,
		arg.TelegramID,
	)
	var i User
	err := row.Scan(
		&i.TelegramID,
		&i.TgUsername,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
